config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}
  root 'itineraries#index'

  resources :itineraries

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates :start_date, :end_date, :city, :country, presence: true

  after_create :fetch_events

  def fetch_events
    query = "http://api.eventful.com/rest/events/search?app_key=v6mgZRgw6VGgNmVn&location=#{city},%20#{country}&date=#{start_date}00-#{end_date}00"
    data = RestClient.get(query)
    result = Hash.from_xml data

    result["search"]["events"]["event"].each do |event|
      events.create title: event["title"], description: event["description"], venue: event["venue_name"], start_time: event["start_time"], end_time: event["stop_time"], all_day: event["all_day"] != 0, address: event["venue_address"]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :itineraries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :authenticate_user!

  def index
    @itineraries = current_user.itineraries
  end

  def new
    @itinerary = Itinerary.new
  end

  def create
    @itinerary = current_user.itineraries.build itinerary_safe_params
    if @itinerary.save
      redirect_to itineraries_path
    else
      flash_first_error(@itinerary)
      render "new"
    end
  end

  def show
    @itinerary = current_user.itineraries.find params[:id]
  end

  private

  def itinerary_safe_params
    params.require(:itinerary).permit(:start_date, :end_date, :city, :country)
  end

  def flash_first_error(itinerary)
    flash[:error] = itinerary.errors.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/itineraries/index.html.erb
<h1>List of User's Itineraries</h1>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% end %>

<ul>
  <% @itineraries.each do |itinerary| %>
    <li> <%= itinerary.start_date %> <%= itinerary.end_date %> <%= link_to "#{itinerary.city} #{itinerary.country}", itinerary%>
    </li>
  <% end %>
<ul>

<%= link_to "Create new itinerary", new_itinerary_path %>

app/views/itineraries/new.html.erb
<%= flash[:error] %>
<%= form_for(@itinerary) do |f| %>
  <fieldset>
    <div>
      <%= f.label :start_date %>
      <%= f.text_field :start_date %>
    </div>
    <div>
      <%= f.label :end_date %>
      <%= f.text_field :end_date %>
    </div>
    <div>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div>
      <%= f.label :country %>
      <%= f.text_field :country %>
    </div>

  </fieldset>
  <%=  f.submit "Submit" %>
<% end %>

app/views/itineraries/show.html.erb
<h1>Events for <%= @itinerary.city %>, <%= @itinerary.country %> during <%= @itinerary.start_date %> - <%= @itinerary.end_date %></h1>

<% @itinerary.events.each do |event| %>
  <ul>
    <li><%= "Title: #{event.title}" %></li>
    <li><%= raw event.description %></li>
    <li><%= "Venue: #{event.venue}" %></li>
    <li><%= "Start Time: #{event.start_time}" %></li>
    <li><%= "End Time: #{event.end_time}" %></li>
    <li><%= "All Day: #{event.all_day}" %></li>
    <li><%= "Address: #{event.address}" %><li>
  </ul>
<% end %>

<%= link_to "List of Itineraries", itineraries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThingsToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>